apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dcumi0jgw-nodejs
  janus-idp.io/tekton: dcumi0jgw-nodejs
  backstage.io/kubernetes-id: dcumi0jgw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dcumi0jgw-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
